version: '3.8'

services:
  weather-discord-bot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - NOTIFICATION_CHANNEL_ID=${NOTIFICATION_CHANNEL_ID}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3